// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGiszU_nb6iFyXKyZoo1A2e0OObJkp9Nk',
    appId: '1:903492466144:web:d01fa282978ece36ea6785',
    messagingSenderId: '903492466144',
    projectId: 'muklist-login-test',
    authDomain: 'muklist-login-test.firebaseapp.com',
    storageBucket: 'muklist-login-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEB4v8IxAcGnuzQfR2UC0eaufUaYm1MuU',
    appId: '1:903492466144:android:ccee77103a637eaaea6785',
    messagingSenderId: '903492466144',
    projectId: 'muklist-login-test',
    storageBucket: 'muklist-login-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1dagf22qs0pu32fSrXKLMIxFQZWDBjas',
    appId: '1:903492466144:ios:a9bef4de9bd37b10ea6785',
    messagingSenderId: '903492466144',
    projectId: 'muklist-login-test',
    storageBucket: 'muklist-login-test.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1dagf22qs0pu32fSrXKLMIxFQZWDBjas',
    appId: '1:903492466144:ios:a9bef4de9bd37b10ea6785',
    messagingSenderId: '903492466144',
    projectId: 'muklist-login-test',
    storageBucket: 'muklist-login-test.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGiszU_nb6iFyXKyZoo1A2e0OObJkp9Nk',
    appId: '1:903492466144:web:fabf6b13e986fb5dea6785',
    messagingSenderId: '903492466144',
    projectId: 'muklist-login-test',
    authDomain: 'muklist-login-test.firebaseapp.com',
    storageBucket: 'muklist-login-test.firebasestorage.app',
  );

}